spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    username: root
    password: root
    
    
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
  
  security:
    user:
      name: gaurav
      password: gaurav123   

management:
  endpoints:
    web:
      exposure:
        include: "*" 
        exclude:
          - heapdump
      base-path: /blog-actuator
  endpoint:
    shutdown:
      enabled: true
      

  info:
    env:
      enabled: true 
        
info:
  build:
    version: v1
  app:
    version: v2